### ISSUE TITLE
Constraint sliders steps are too large

### ISSUE THREAD

**Issue by jdilger** [sepal-contrib/se.plan#128]
> Hi all, 
>I've been trying to run scenarios for a few countries in Asia on se.plan and just wanted to share/document an observation about the tool. When selecting socio-economic constraints, such as "Accessibility to cities" and "Population density", the settings for the slide bar are restricted to certain values which don't allow the user to insert a desired threshold. Is this something we could change on the tool? 
>Thank you in advance!

Received this feature request from a colleague who is using se.plan. @12rambau any thoughts on how we might adjust the sliders to allow for better control of a constraints range? The main issue is that since some of these layers have log skewed data most of the data can be skipped in the first step.

**Comment by 12rambau** [comment]
So what I did is the following: 
- situation 1: the number we want to display are bigger than 100, then I only display 1 digit and use a .1 step
- situation 2: the numbers are small and I display 2 digits and use .01 step 

I don't want to go down the path of using a box next to the slider to update the numbers by hands. I've done it in another application and it's only leading to issues when users use strange values (white spaces, _, str instead of number). The main issue being that html doesn't know how to identify a float (if it was only integer that would have been trivial).

Let me know what you think
