### ISSUE TITLE
rainfall dataset is missing to many data

### ISSUE THREAD

**Issue by 12rambau** [sepal-contrib/se.plan#136]
The whole north part of kazakstan is missing 

```javascript
var image = ee.Image("projects/john-ee-282116/assets/fao-restoration/features/chirps_00_20_mean")
Map.addLayer(image)
```

@jdilger as you generated this layer would it be possible to check the geometry you used to export it as an asset? and eventually run the script again using the LMIC bounding box ? (https://github.com/sepal-contrib/se.plan/blob/5e4b053c68468793c2c8011d463259e2afdc525a/get_all_values.ipynb?short_path=d472003#L129)

**Comment by jdilger** [comment]
I'll look into it this week. Been off on holiday. If I remember correctly, I think the issue was with the CHIRPS data itself (e.g. that mission does not collect data into that extent).  Which then prompted some discussion on what the next best alternative would be and apparently was forgotten. I'll double check and follow up here and/or via email.

**Comment by jdilger** [comment]
Will be replaced with 30 year mean using ECMWF/ERA5_LAND/MONTHLY

**Comment by jdilger** [comment]
Switched to ERA5_LAND 30-year mean. 
todo:

- [ ] update documentaion

**Comment by 12rambau** [comment]
@jdilger is it an annual mean or a monthly mean ?

**Comment by jdilger** [comment]
I did the sum of monthly rainfall per year and then averaged it by all years. Happy to reformulate it if you think there's a better method to go about it. 

https://code.earthengine.google.com/31cb2dcee9b2bfe4bf2e98e3a8b81032

**Comment by 12rambau** [comment]
That's perfect I just wanted to know if a Unit change was required. I updated the documentation so I'm closing this one
