### ISSUE TITLE
No UI notebook does not render all UI elements in Jupyter Lab

### ISSUE THREAD

**Issue by jdilger** [sepal-contrib/se.plan#147]
I am noticing that certain UI elements (AOI, questionnaire, and map tile) do not render in Jupyter Lab for the no_ui notebook. @12rambau have you encountered this before? Switching to a Jupyter Notebook instance renders all UI elements as intended, but it's a bit cumbersome for development in SPEAL. I'm interested to hear if you have any insights or general suggestions for working on se.plan within SPEAL.

**Comment by 12rambau** [comment]
This problem is related to incompatibilies issues between the SEPAL jupyterLab environment and the ipyleaflet version set in the venv. It's always working in Juoyter Notebook and the problem is solved and reapears on regular basis when new versions are installed in SEPAL. 

I will tag it as non Fix as it's a bigger compatibility problem that we need to discuss with the SEPAL core team. 

thanks for reporting
